//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirPortEntities : DbContext
    {
        public AirPortEntities()
            : base("name=AirPortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<AirPlanes> AirPlanes { get; set; }
        public virtual DbSet<AirPlaneTypes> AirPlaneTypes { get; set; }
        public virtual DbSet<AirPort> AirPort { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Login_Password> Login_Password { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Pilots> Pilots { get; set; }
        public virtual DbSet<Seets_On_The_Plane> Seets_On_The_Plane { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets_Sold> Tickets_Sold { get; set; }
    }
}
