//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airs
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPlaneTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirPlaneTypes()
        {
            this.AirPlanes = new HashSet<AirPlanes>();
        }
    
        public string Types { get; set; }
        public int All_Rows { get; set; }
        public int Bussnes_Rows { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirPlanes> AirPlanes { get; set; }
    }
}
