//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Tickets_Sold = new HashSet<Tickets_Sold>();
        }
    
        public int Flight_Num { get; set; }
        public System.DateTime Filight_Date { get; set; }
        public string Point_Of_Departure { get; set; }
        public string Destination { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public int AirPlane_Num { get; set; }
        public int Pilot_Num { get; set; }
        public int AirPortTO_Num { get; set; }
        public int AirPortFrom_Num { get; set; }
    
        public virtual AirPlanes AirPlanes { get; set; }
        public virtual Pilots Pilots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets_Sold> Tickets_Sold { get; set; }
    }
}
