//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seets_On_The_Plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seets_On_The_Plane()
        {
            this.Tickets_Sold = new HashSet<Tickets_Sold>();
        }
    
        public int AirPlane_Num { get; set; }
        public int Place_Num { get; set; }
        public int Row_Num { get; set; }
    
        public virtual AirPlanes AirPlanes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets_Sold> Tickets_Sold { get; set; }
    }
}
