//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets_Sold
    {
        public int Ticket_Num { get; set; }
        public int Flight_Num { get; set; }
        public int Passport_Num { get; set; }
        public int Passport_Series { get; set; }
        public System.DateTime Flight_Date { get; set; }
        public int Place_Num { get; set; }
        public int Row_Num { get; set; }
        public int AirPlane_Num { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passengers Passengers { get; set; }
        public virtual Seets_On_The_Plane Seets_On_The_Plane { get; set; }
    }
}
